import {
  Wallet,
  PiggyBank,
  TrendingUp,
  LineChart,
  LayoutGrid,
  ArrowLeftRight,
  Tags,
  Landmark,
  Settings2,
  Home,
  ShoppingCart,
  Car,
  PartyPopper,
  HeartPulse,
  Package,
  Briefcase,
  Fuel,
  Film,
  Plus,
  ArrowUpRight,
  ArrowDownRight,
  ChevronLeft,
  ChevronRight,
  X,
  Trash2,
  Pencil,
  Check,
  Filter,
  Calendar,
  Utensils,
  Plane,
  Gift,
  Smartphone,
  Dumbbell,
  GraduationCap,
  PawPrint,
  Shirt,
  Coffee,
  Bus,
  Heart,
  Zap,
  Wifi,
  BookOpen,
  CreditCard,
  Gamepad2,
  Music,
  ShoppingBag,
  CircleHelp,
} from 'lucide-react'

// Registro central: el resto de la app referencia iconos por nombre,
// así el estilo (grosor de trazo, tamaño) queda unificado en un sitio.
const registry = {
  // navegación
  dashboard: LayoutGrid,
  transactions: ArrowLeftRight,
  categories: Tags,
  accounts: Landmark,
  investments: TrendingUp,
  settings: Settings2,
  // cuentas
  wallet: Wallet,
  piggy: PiggyBank,
  trending: LineChart,
  // acciones / UI
  plus: Plus,
  up: ArrowUpRight,
  down: ArrowDownRight,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  close: X,
  delete: Trash2,
  edit: Pencil,
  check: Check,
  filter: Filter,
  calendar: Calendar,
  // categorías / movimientos
  home: Home,
  cart: ShoppingCart,
  car: Car,
  leisure: PartyPopper,
  health: HeartPulse,
  package: Package,
  salary: Briefcase,
  fuel: Fuel,
  film: Film,
  utensils: Utensils,
  plane: Plane,
  gift: Gift,
  phone: Smartphone,
  gym: Dumbbell,
  education: GraduationCap,
  pet: PawPrint,
  clothes: Shirt,
  coffee: Coffee,
  bus: Bus,
  heart: Heart,
  energy: Zap,
  wifi: Wifi,
  book: BookOpen,
  card: CreditCard,
  games: Gamepad2,
  music: Music,
  shopping: ShoppingBag,
}

function Icon({ name, size = 20, strokeWidth = 1.85, ...props }) {
  const Glyph = registry[name] ?? CircleHelp
  return <Glyph size={size} strokeWidth={strokeWidth} aria-hidden {...props} />
}

export default Icon
